-- vim.cmd 'source ~/.config/nvim/init_old.vim'
require "user.settings"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.notify"
require "user.telescope"
require "user.treesitter"
require "user.floaterm"
--require "user.dap"
require "user.null-ls"
require "user.barbar"
require "user.lightspeed"
-- require "user.autocommands"
-- require "user.colorscheme"
-- require "user.autopairs"
-- require "user.comment"
require "user.nvim-tree"
require "user.gitsigns"
-- require "user.bufferline"
-- require "user.lualine"
-- require "user.toggleterm"
-- require "user.project"
-- require "user.impatient"
-- require "user.indentline"
-- require "user.alpha"
-- require "user.whichkey"
-- require "user.quickscope"
-- require "user.hop"
-- require "user.matchup"
-- require "user.numb"
-- require "user.dial"
-- require "user.colorizer"
-- require "user.spectre"
-- require "user.zen-mode"
-- require "user.neoscroll"
-- require "user.todo-comments"
-- require "user.bookmark"
-- require "user.renamer"
-- require "user.symbol-outline"
-- require "user.git-blame"
-- require "user.gist"
-- require "user.gitlinker"
-- require "user.surround"
-- require "user.ts-context"
-- require "user.registers"
-- require "user.telescope-file-browser"
-- require "user.sniprun"
-- require "user.functions"
-- require "user.copilot"
-- require "user.gps"
-- require "user.illuminate"
-- require "user.dap"
-- require "user.lir"
-- require "user.jabs"
-- require "user.cybu"
-- require "user.winbar"
-- require "user.options"
-- require "user.nvim-webdev-icons"
